### ISSUE TITLE
sqlite3.OperationalError: no such column: qm_conformers.qcarchive_id

### ISSUE THREAD

**Issue by amcisaac** [mattwthompson/ib#16]
I am getting this error when I try to run the benchmarking code. The code appears to create and optimize the MoleculeStore, but when it calls `get_dde` this error arises. I tried reading the `sqlite` file into a new script and I see the MM records present with both conformers and energies. I was able to access the MM conformers with `store.get_mm_conformers_by_molecule_id` and I was able to access the energies by accessing the records with `store.get_mm_energies_by_molecule_id` and then taking the `energy` property, however I got the error again when calling `store.get_mm_energies_by_molecule_id` directly.

When I tried to call `get_dde` on the store, it did not recognize the MM records as being present and tried to re-optimize them all.

I got the error when running benchmarks on the big industry dataset, but I was able to create a small test example that is much faster to run.

This is the code i’m using: https://github.com/openforcefield/sage-2.2.0/blob/main/05_benchmark_forcefield/benchmark.py

Conda env: https://github.com/openforcefield/sage-2.2.0/blob/main/05_benchmark_forcefield/ib-env-full.yaml
(Note, I also tried it with your environment in this repo, as well as with the last two versions of SQLalchemy, and had the same issue)

The small test is here: https://github.com/openforcefield/sage-2.2.0/tree/main/05_benchmark_forcefield/test

With this dataset: https://github.com/openforcefield/sage-2.2.0/blob/main/05_benchmark_forcefield/datasets/OpenFF-Aniline-Para-Opt-v1.0.json

```Traceback (most recent call last):
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: qm_conformers.qcarchive_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dfs6/pub/amcisaac/sage-2.2.0/05_benchmark_forcefield/benchmark.py", line 58, in <module>
    main()
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/dfs6/pub/amcisaac/sage-2.2.0/05_benchmark_forcefield/benchmark.py", line 50, in main
    store.get_dde(forcefield).to_csv(f"{out_dir}/dde.csv")
  File "/dfs6/pub/amcisaac/ib/ibstore/_store.py", line 492, in get_dde
    mm_energies = self.get_mm_energies_by_molecule_id(molecule_id, force_field)
  File "/dfs6/pub/amcisaac/ib/ibstore/_store.py", line 324, in get_mm_energies_by_molecule_id
    .all()
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2693, in all
    return self._iter().all()  # type: ignore
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2847, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/data/homezvol3/amcisaac/miniconda3/envs/ib-env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: qm_conformers.qcarchive_id
[SQL: SELECT mm_conformers.energy AS mm_conformers_energy 
FROM mm_conformers 
WHERE mm_conformers.parent_id = ? AND mm_conformers.force_field = ? ORDER BY qm_conformers.qcarchive_id]
[parameters: (7, 'openff_unconstrained-2.2.0-rc1.offxml')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)```

**Comment by mattwthompson** [comment]
I was very confused until I came across this:

https://github.com/mattwthompson/ib/blob/de80859f37b345845f9a7ba5240a4279e5913458/ibstore/_store.py#L318-L326

Notice that it's querying _M_M conformers but trying to order by the QCArchive IDs of the _Q_M conformer records.

I'm still confused - shouldn't this have failed in one of the tests? - but this might be a fix.

**Comment by mattwthompson** [comment]
I tagged 0.0.3 which I believe resolved this - let me know if that's not the case

https://github.com/mattwthompson/ib/releases/tag/0.0.3
